### ISSUE TITLE
Clashes in release 1.2

### ISSUE THREAD

**Issue by TheoGuyard** [benchopt/benchmark_lasso#126]
The benchmark is broken with the release 1.2. For instance, `snapml.py` calls functions in `from benchopt.utils.sys_info` that do not exist. These clashes seems to be resolved in the `main` branch when installing `benchopt` with `pip install -U git+https://github.com/benchopt/benchopt`.

```
(benchopt) benchmark_lasso (julia-pgd-typed) benchopt install .    
Installing 'benchmark_lasso' requirements
Traceback (most recent call last):
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/bin/benchopt", line 8, in <module>
    sys.exit(benchopt())
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/cli/main.py", line 323, in install
    benchmark.validate_solver_patterns(solver_names)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/benchmark.py", line 102, in validate_solver_patterns
    all_solvers = _list_all_parametrized_names(*self.get_solvers())
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/benchmark.py", line 92, in get_solvers
    return self._list_benchmark_classes(BaseSolver)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/benchmark.py", line 146, in _list_benchmark_classes
    cls = _load_class_from_module(
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/utils/dynamic_modules.py", line 60, in _load_class_from_module
    module = _get_module_from_file(module_filename, benchmark_dir)
  File "/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/utils/dynamic_modules.py", line 33, in _get_module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tguyard/Documents/Github/benchmark_lasso/solvers/snapml.py", line 2, in <module>
    from benchopt.utils.sys_info import get_cuda_version
ImportError: cannot import name 'get_cuda_version' from 'benchopt.utils.sys_info' (/Users/tguyard/opt/miniconda3/envs/benchopt/lib/python3.9/site-packages/benchopt/utils/sys_info.py)
```

**Comment by mathurinm** [comment]
@TheoGuyard can you close if it's solved ? We released 1.3 now
