### ISSUE TITLE
Issue with 4 solvers when running the benchmark

### ISSUE THREAD

**Issue by zaccharieramzi** [benchopt/benchmark_lasso#14]
I am trying to run the benchmark, with the following command: `benchopt run --env --recreate ./` (I use recreate to make sure the env is clean for this issue).

I get 4 errors on the following solvers: `cvxpy`, `ModOpt`, `celer` and `sklearn`
For the boston dataset:

- `cvxpy`:
```
Traceback (most recent call last):
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/pdb_helpers.py", line 24, in exception_handler
    yield
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 253, in run_one_solver
    stop_val_curve, objective_value = run_one_stop_val_cached(
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 129, in run_one_stop_val
    cost, objective_value = run_one_repetition_cached(*args)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 62, in run_one_repetition
    solver.run(stop_val)
  File "solvers/cvxpy.py", line 39, in run
    self.problem.solve(max_iters=n_iter, verbose=False)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 401, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 819, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1131, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
```

- `sklearn` (also for `simulated`):

```
Traceback (most recent call last):
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/pdb_helpers.py", line 24, in exception_handler
    yield
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 253, in run_one_solver
    stop_val_curve, objective_value = run_one_stop_val_cached(
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 129, in run_one_stop_val
    cost, objective_value = run_one_repetition_cached(*args)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 62, in run_one_repetition
    solver.run(stop_val)
  File "solvers/sklearn.py", line 26, in run
    self.clf.fit(self.X, self.y)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 844, in fit
    self.path(X, y[:, k],
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 530, in enet_path
    model = cd_fast.enet_coordinate_descent(
  File "sklearn/linear_model/_cd_fast.pyx", line 102, in sklearn.linear_model._cd_fast.enet_coordinate_descent
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

For finance, `cvxpy` skips with the following reason: `Reason: problem too large.` and `sklearn` times out.

For finance, 
- `ModOpt` :
```
Traceback (most recent call last):
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/pdb_helpers.py", line 24, in exception_handler
    yield
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 253, in run_one_solver
    stop_val_curve, objective_value = run_one_stop_val_cached(
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 129, in run_one_stop_val
    cost, objective_value = run_one_repetition_cached(*args)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 62, in run_one_repetition
    solver.run(stop_val)
  File "solvers/modopt_pogm.py", line 48, in run
    L = np.linalg.norm(self.X, ord=2) ** 2
  File "<__array_function__ internals>", line 5, in norm
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2610, in norm
    raise ValueError("Improper number of dimensions to norm.")
ValueError: Improper number of dimensions to norm.
```

- `celer` (only `reg=0.1` and `reg=0.5`):
```
Traceback (most recent call last):
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/pdb_helpers.py", line 24, in exception_handler
    yield
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 253, in run_one_solver
    stop_val_curve, objective_value = run_one_stop_val_cached(
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 129, in run_one_stop_val
    cost, objective_value = run_one_repetition_cached(*args)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/runner.py", line 62, in run_one_repetition
    solver.run(stop_val)
  File "solvers/celer.py", line 32, in run
    self.lasso.fit(self.X, self.y)
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 844, in fit
    self.path(X, y[:, k],
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/celer/dropin_sklearn.py", line 132, in path
    results = celer_path(
  File "/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/celer/homotopy.py", line 268, in celer_path
    compute_Xw(
  File "celer/cython_utils.pyx", line 330, in celer.cython_utils.__pyx_fuse_1compute_Xw
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

I think the issue with the `ModOpt` solvers is just that the data is sparse for the finance dataset.
I can just try to skip them for sparse data (like is done for others), if that's alright, and submit a PR.

Re the other solvers I don't really know (and I don't know whether the issue happens only on my end).

I also had the following error, repeated for multiple lines, for `sklearn`:
```
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
```

**Comment by agramfort** [comment]
yes please send a PR. One idea is to have sparse dataset in Simulated to detect if certain solvers do not skip properly for sparse data.

**Comment by zaccharieramzi** [comment]
Sure, but as I said this will only solve one problem, but 3 other solvers will still have the issues mentionned.

**Comment by agramfort** [comment]
CIs should catch this

>

**Comment by mathurinm** [comment]
Hi @zaccharieramzi 
Can you still reproduce with main versions of benchopt and benchmark_lasso ?

**Comment by zaccharieramzi** [comment]
@mathurinm for `benchOpt` do you mean master or the pypi release?

Currently with the pypi release I have the following (unrelated) error:


```
Traceback (most recent call last):
  File "/home/zr258722/workspace/benchmark_lasso/venv/bin/benchopt", line 8, in <module>
    sys.exit(benchopt())
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/cli/main.py", line 92, in run
    benchmark.validate_solver_patterns(solver_names+forced_solvers)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/benchmark.py", line 243, in validate_solver_patterns
    solvers = self.list_benchmark_solvers()
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/benchmark.py", line 98, in list_benchmark_solvers
    return self._list_benchmark_classes(BaseSolver)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/benchmark.py", line 84, in _list_benchmark_classes
    cls = _load_class_from_module(module_filename, class_name)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/utils/dynamic_modules.py", line 46, in _load_class_from_module
    module = _get_module_from_file(module_filename)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/utils/dynamic_modules.py", line 22, in _get_module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "solvers/glum.py", line 4, in <module>
    from benchopt.stopping_criterion import SufficientProgressCriterion
ImportError: cannot import name 'SufficientProgressCriterion' from 'benchopt.stopping_criterion' (/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/benchopt/stopping_criterion.py)
```

**Comment by mathurinm** [comment]
Sorry I I meant the master branch (it has not yet been renamed to main following the new github convention)

**Comment by zaccharieramzi** [comment]
With the 2 master versions, I have the following error, so I am still not able to reproduce the issue at hand:

```
(venv) ➜  benchmark_lasso git:(main) conda env list
# conda environments:
#
base                  *  /volatile/anaconda3
benchopt_benchmark_lasso     /volatile/anaconda3/envs/benchopt_benchmark_lasso

(venv) ➜  benchmark_lasso git:(main) benchopt run --env  ./
Traceback (most recent call last):
  File "/home/zr258722/workspace/benchmark_lasso/venv/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zr258722/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/zr258722/workspace/benchOpt/benchopt/cli/main.py", line 144, in run
    raise RuntimeError(
RuntimeError: The default env 'benchopt_benchmark_lasso' for benchmark benchmark_lasso does not exist. Make sure to run `benchopt install -e .` to create the benchmark and install the dependencies.
```

**Comment by mathurinm** [comment]
OK, weird.

Why does your shell line starts with `(venv)` even though only `base` and `benchopt_benchmark_lasso` are listed as conda environments ? `venv` is not a conda environement ?

**Comment by zaccharieramzi** [comment]
no I usually work with `virtualenv`, `venv` was created with `virtualenv -p /usr/bin/python3.9 venv`

**Comment by agramfort** [comment]
@zaccharieramzi are you using benchopt main branch locally?

**Comment by zaccharieramzi** [comment]
Yes

**Comment by mathurinm** [comment]
Maybe virtualenv conflicts in a way with your conda env ? It would not be surprising to me.

I created a virtualenv too and `(venv) (base) ➜  lasso git:(main) ✗ benchopt install -e . --recreate -s sklearn -s celer
` work. 
I'm surprised because by console line shows both the venv and the base conda environment, do you know why it's not the case for you ?
```
(base) ➜  ~ source venv/bin/activate
(venv) (base) ➜  ~ 
``` 

Does `benchopt install -s sklearn -s celer` work ?

**Comment by zaccharieramzi** [comment]
Indeed, it's because you need to have conda base activated first. 
The problem in my case was that the conda init had modified my bashrc file in order to do so, but I use zsh.

When I activate conda first, I can run the benchmark with no bugs but no benchmarks are run:

```
BenchOpt is running
finance                                                                                                                                        
Dataset finance is not installed.                                                                                                              
leukemia                                                                                                                                       
Dataset leukemia is not installed.                                                                                                             
libsvm[dataset=bodyfat]                                                                                                                        
Dataset libsvm[dataset=bodyfat] is not installed.                                                                                              
libsvm[dataset=leukemia]                                                                                                                       
Dataset libsvm[dataset=leukemia] is not installed.                                                                                             
Simulated[n_samples=100,n_features=5000,rho=0]                                                                                                 
|--Lasso Regression[reg=0.05,fit_intercept=True]                                                                                               
|----Blitz: not installed                                                                                                                      
|----cd: not installed                                                                                                                         
|----Celer: not installed                                                                                                                      
|----Cyanure: not installed                                                                                                                    
|----glmnet: not installed                                                                                                                     
|----glum: not installed                                                                                                                       
|----Julia-PGD: not installed                                                                                                                  
|----L-BFGS-B: skip                                                                                                                            
Reason: L-BFGS-B does not handle fit_intercept
|----Lightning: not installed                                                                                                                  
|----Python-PGD[use_acceleration=False]: skip                                                                                                  
Reason: Python-PGD does not handle fit_intercept
|----Python-PGD[use_acceleration=True]: skip                                                                                                   
Reason: Python-PGD does not handle fit_intercept
|----R-PGD: not installed                                                                                                                      
|----sklearn: not installed                                                                                                                    
|----spams: not installed                                                                                                                      
|--Lasso Regression[reg=0.05,fit_intercept=False]                                                                                              
|----Blitz: not installed                                                                                                                      
|----cd: not installed                                                                                                                         
|----Celer: not installed                                                                                                                      
|----Cyanure: not installed                                                                                                                    
|----glmnet: not installed                                                                                                                     
|----glum: not installed                                                                                                                       
|----Julia-PGD: not installed                                                                                                                  
|----L-BFGS-B: interrupted 
```

When I try to run the command `benchopt install . -s sklearn -s celer`, it takes a veeery long time (still running even though I started 20' ago):

```
Installing 'benchmark_lasso' requirements
Install in the current env 'base'? [y/N]: y
# Install
Collecting packages:
- 'Simulated' already available
... done
Installing required packages for:
- Celer
- sklearn
- finance
- leukemia
- libsvm
...
```

**Comment by mathurinm** [comment]
If you have not already done it, you can do conda init zsh, or source your bashrc in your zshrc

The package list is printed at once so it's not necessarily libsvm which is taking time.

Can you try installing in a fresh environment, with `benchopt install . -s sklearn -s celer --recreate` ?

**Comment by zaccharieramzi** [comment]
hahaha I think I am fine without conda, but I indeed didn't know this command.

I tried with `benchopt install --env-name benchopt_benchmark_lasso . -s sklearn -s celer --recreate`, but I am getting the following error when installing celer:
```
Building wheels for collected packages: celer
  Building wheel for celer (setup.py): started
  Building wheel for celer (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/zaccharie/workspace/benchmark_lasso/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/setup.py'"'"'; __file__='"'"'/tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-np5ep21u
       cwd: /tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/celer
  copying celer/__init__.py -> build/lib.linux-x86_64-3.9/celer
  copying celer/dropin_sklearn.py -> build/lib.linux-x86_64-3.9/celer
  copying celer/plot_utils.py -> build/lib.linux-x86_64-3.9/celer
  copying celer/homotopy.py -> build/lib.linux-x86_64-3.9/celer
  creating build/lib.linux-x86_64-3.9/celer/datasets
  copying celer/datasets/ml_uci.py -> build/lib.linux-x86_64-3.9/celer/datasets
  copying celer/datasets/__init__.py -> build/lib.linux-x86_64-3.9/celer/datasets
  copying celer/datasets/libsvm.py -> build/lib.linux-x86_64-3.9/celer/datasets
  copying celer/datasets/climate.py -> build/lib.linux-x86_64-3.9/celer/datasets
  copying celer/datasets/simulated.py -> build/lib.linux-x86_64-3.9/celer/datasets
  creating build/lib.linux-x86_64-3.9/celer/utils
  copying celer/utils/__init__.py -> build/lib.linux-x86_64-3.9/celer/utils
  copying celer/utils/testing.py -> build/lib.linux-x86_64-3.9/celer/utils
  running build_ext
  cythoning celer/lasso_fast.pyx to celer/lasso_fast.cpp
  cythoning celer/cython_utils.pyx to celer/cython_utils.cpp
  /home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/celer/cython_utils.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  cythoning celer/PN_logreg.pyx to celer/PN_logreg.cpp
  cythoning celer/multitask_fast.pyx to celer/multitask_fast.cpp
  cythoning celer/group_fast.pyx to celer/group_fast.cpp
  building 'celer.lasso_fast' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/celer
  /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/include -fPIC -I/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -I/home/zaccharie/workspace/benchmark_lasso/venv/include/python3.9 -c celer/lasso_fast.cpp -o build/temp.linux-x86_64-3.9/celer/lasso_fast.o -O3
  In file included from /usr/include/python3.9/Python.h:8,
                   from celer/lasso_fast.cpp:6:
  /usr/include/python3.9/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.9/pyconfig.h: No such file or directory
      3 | #  include <x86_64-linux-gnu/python3.9/pyconfig.h>
        |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for celer
  Running setup.py clean for celer
Failed to build celer
Installing collected packages: celer
    Running setup.py install for celer: started
    Running setup.py install for celer: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/zaccharie/workspace/benchmark_lasso/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/setup.py'"'"'; __file__='"'"'/tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qcvb6l_l/install-record.txt --single-version-externally-managed --compile --install-headers /home/zaccharie/workspace/benchmark_lasso/venv/include/site/python3.9/celer
         cwd: /tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/
    Complete output (38 lines):
    running install
    /home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/celer
    copying celer/__init__.py -> build/lib.linux-x86_64-3.9/celer
    copying celer/dropin_sklearn.py -> build/lib.linux-x86_64-3.9/celer
    copying celer/plot_utils.py -> build/lib.linux-x86_64-3.9/celer
    copying celer/homotopy.py -> build/lib.linux-x86_64-3.9/celer
    creating build/lib.linux-x86_64-3.9/celer/datasets
    copying celer/datasets/ml_uci.py -> build/lib.linux-x86_64-3.9/celer/datasets
    copying celer/datasets/__init__.py -> build/lib.linux-x86_64-3.9/celer/datasets
    copying celer/datasets/libsvm.py -> build/lib.linux-x86_64-3.9/celer/datasets
    copying celer/datasets/climate.py -> build/lib.linux-x86_64-3.9/celer/datasets
    copying celer/datasets/simulated.py -> build/lib.linux-x86_64-3.9/celer/datasets
    creating build/lib.linux-x86_64-3.9/celer/utils
    copying celer/utils/__init__.py -> build/lib.linux-x86_64-3.9/celer/utils
    copying celer/utils/testing.py -> build/lib.linux-x86_64-3.9/celer/utils
    running build_ext
    skipping 'celer/lasso_fast.cpp' Cython extension (up-to-date)
    skipping 'celer/cython_utils.cpp' Cython extension (up-to-date)
    skipping 'celer/PN_logreg.cpp' Cython extension (up-to-date)
    skipping 'celer/multitask_fast.cpp' Cython extension (up-to-date)
    skipping 'celer/group_fast.cpp' Cython extension (up-to-date)
    building 'celer.lasso_fast' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/celer
    /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/include -fPIC -I/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -I/home/zaccharie/workspace/benchmark_lasso/venv/include/python3.9 -c celer/lasso_fast.cpp -o build/temp.linux-x86_64-3.9/celer/lasso_fast.o -O3
    In file included from /usr/include/python3.9/Python.h:8,
                     from celer/lasso_fast.cpp:6:
    /usr/include/python3.9/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.9/pyconfig.h: No such file or directory
        3 | #  include <x86_64-linux-gnu/python3.9/pyconfig.h>
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/home/zaccharie/anaconda3/envs/benchopt_benchmark_lasso/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zaccharie/workspace/benchmark_lasso/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/setup.py'"'"'; __file__='"'"'/tmp/pip-install-us0i2000/celer_4a4a540d41aa41568c2f1de90e212b23/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qcvb6l_l/install-record.txt --single-version-externally-managed --compile --install-headers /home/zaccharie/workspace/benchmark_lasso/venv/include/site/python3.9/celer Check the logs for full command output.
```

I have tried the following fixes from (https://github.com/okfn/piati/issues/65):
- `sudo apt-get install python3.9-dev`
- `export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python3.9/"`

**Comment by mathurinm** [comment]
The `ValueError: buffer source array is read-only`  encountered in celer and sklearn may come from Modopt making the input data immutable. There is an option in their dev branch to do it, as soon as it lands on PyPI we'll integrate it in #45
