### ISSUE TITLE
Error with celer after fresh install

### ISSUE THREAD

**Issue by cassiofragadantas** [benchopt/benchmark_lasso#77]
I have removed and then reinstalled bechmark lasso from scratch

```
$ conda env remove -n benchopt_benchmark_lasso
$ benchopt install -e ./benchmark_lasso
$ conda activate benchopt_benchmark_lasso
```

When trying to run benchopt info I get the following error for celer

```
$ benchopt info ./benchmark_lasso -s celer
Info regarding the benchmark 'benchmark_lasso'
Traceback (most recent call last):
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchopt/benchopt/cli/helpers.py", line 235, in info
    benchmark.validate_solver_patterns(solver_names)
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchopt/benchopt/benchmark.py", line 102, in validate_solver_patterns
    all_solvers = _list_all_parametrized_names(*self.get_solvers())
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchopt/benchopt/benchmark.py", line 92, in get_solvers
    return self._list_benchmark_classes(BaseSolver)
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchopt/benchopt/benchmark.py", line 146, in _list_benchmark_classes
    cls = _load_class_from_module(
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchopt/benchopt/utils/dynamic_modules.py", line 60, in _load_class_from_module
    module = _get_module_from_file(module_filename, benchmark_dir)
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchopt/benchopt/utils/dynamic_modules.py", line 33, in _get_module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cfraga/Dropbox/Study/Postdoc/source/2022/benchmark_lasso/solvers/celer.py", line 9, in <module>
    from celer import Lasso
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/celer/__init__.py", line 3, in <module>
    from .homotopy import celer_path
  File "/home/cfraga/anaconda3/envs/benchopt_benchmark_lasso/lib/python3.8/site-packages/celer/homotopy.py", line 13, in <module>
    from .lasso_fast import celer
  File "celer/lasso_fast.pyx", line 1, in init celer.lasso_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

It seems to be related to the Numpy version. But weirdly, It re-works after manually installing celer
```
$ conda install celer
```
This conda install did not modify any of the previously installed packages.

After this, benchopt info outputs the following (note the RuntimeError concerning numpy version, is it relevant?)
```
$ benchopt info ./benchmark_lasso -s celer
Info regarding the benchmark 'benchmark_lasso'
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
----------
# SOLVERS
----------
## Celer
✓ available in 'running env'
> requirements:
    pip install celer
----------
```

**Comment by mathurinm** [comment]
@cassiofragadantas this was related to celer wheels being built with versions of numpy that were too recent, it should not longer happen. Reopen if it still does
